 const BASE_URL = "https://hlz-global-reg-boot.herokuapp.com"
//  const BASE_URL = "http://localhost:8080"
export const DOES_USER_EXIST = BASE_URL+"/v1/hlzGlobalReg/doesUserExist"
export const CHECK_PERMISSION = BASE_URL+"/v1/hlzGlobalReg/checkPermission"
export const GET_ALL_DEP_BY_USER_ID = BASE_URL+"/v1/hlzGlobalReg/fetchAllDepById"
export const ADD_DEVOTEE_DATA = "https://hlz-global-reg-boot.herokuapp.com/v1/hlzGlobalReg/saveInput/"
export const PROFILE_PIC_UPLOAD = "https://hlz-global-reg-boot.herokuapp.com/v1/image/upload"
export const CHECK_AUTHENTICATION_URL = "https://api.gaurangavedic.org.in:8443/auth"