export const requiredDataAllFields={
    
    fname: "",
    mname: "",
    lname: "",
    initiatedName: "",
    gender: "MALE",
    dateOfBirth: "1985-12-12",
    maritalStatus: "UNMARRIED",
    bloodGroup: "A +ve",
    language: "HINDI",
    profileImgUrl: "",
    primaryPhone: '',
    whatsappPhone: '',
    email: '',
    currentAddress: {line1:'',line2:'',
    country:'India',
    state:'Delhi',
    city:'New Delhi',
    district:"New Delhi",
    pinCode:''},
    permanentAddress: {line1:'',line2:'',
    country:'India',
    state:'Delhi',
    city:'New Delhi',
    district:"New Delhi",
    pinCode:''},
    facilitator: "",
    spiritualMaster: "",
    chantingRounds: "",
    yearChantingSince: "",
    yearChanting16Rounds: "",
    introducedBy: "",
    preferredServices: "",
    servicesRendered: "",
    education: "NO EDUCATION",
    degreeSpecification:"",
    occupation: "",
    presentDesignation: "",
    skills: "",
    currentCompany: "",
    officeLocation: "",
    birthCity: "",
    birthState: "",
    motherTongue: "Hindi",
    fathersName: "",
    mothersName: "",
    dateOfMarriage:"",
    spouseName:"",
    children:"",
    connectedTo:"",
    modified: false,
    priviledge:"",
    validations:{isValidFname: false,
    isValidGender:false,
    isvalidAshrama:false,
    isValidBirthCity:false,
    isValidBirthState:false,
    isValidDateOfBirth:false,
    isValidCaste:false,
    isValidGotra:false,
    isValidImageURL:false,
    isSubmitDisabled:true,
    isValidPrimaryNo :false,
    isValidEmail:false,
    isValidCurrentAddress:false,
    isValidPermanentAddress:false,
    isValidCenterConnectedTo:false,
    isValidYearChantingSince:false,
    isValidChantingRounds:false,
    isValidCounselor:false,
    isValidFathersName:false,
    isValidMothersName:false,
    isValidSpouseName:false,
    isValidMothersTongue:true,
    isValidEducation:true,
    isValidOccupation:true,
  }
  }

//language: send an array



//priviledge
// SUPER_ADMIN,
//     ADMIN,  
//     GUARDIAN, 
//     VOLUNTEER,
//     USER
