export const requiredDataAllFields={
    
    fname: "",
    mname: "",
    lname: "",
    initiatedName: "",
    gender: "",
    dateOfBirth: "",
    maritalStatus: "",
    bloodGroup: "A +ve",
    language: "HINDI",
    profileImgUrl: "",
    primaryPhone: '',
    whatsAppPhone: '',
    email: '',
    currentAddress: {line1:'',line2:'',
    country:'India',
    state:'State',
    city:'District',
    district:"city",
    pinCode:'100001'},
    permanentAddress: {line1:'',line2:'',
    country:'India',
    state:'State',
    city:'District',
    district:"city",
    pinCode:'100001'},
    facilitator: "",
    spiritualMaster: "",
    chantingRounds: "",
    yearChantingSince: "",
    yearChanting16Rounds: "",
    introducedBy: "",
    preferredServices: "",
    servicesRendered: "",
    education: "NO_EDUCATION",
    degreeSpecification:"",
    occupation: "STUDENT",
    presentDesignation: "",
    skills: "",
    currentCompany: "",
    officeLocation: "",
    birthCity: "",
    birthState: "",
    motherTongue: "Hindi",
    fathersName: "",
    mothersName: "",
    dateOfMarriage:"",
    spouseName:"",
    children:"",
    connectedTo:"",
    modified: false,
    priviledge:"",
    validations:{
    isValidFname: false,
    isValidGender:false,
    isValidDateOfBirth:false,
    isValidMaritalStatus:false,
    isValidImageURL:false,
    isSubmitDisabled:true,
    isValidPrimaryNo :false,
    isValidEmail:false,
    isValidCurrentAddress:false,
    isValidPermanentAddress:false,
    isValidCenterConnectedTo:false,
    isValidYearChantingSince:false,
    isValidYearChanting16Rounds:false,
    isValidChantingRounds:false,
    isValidCounselor:false,
    isValidIntroducedBy:false,
    isValidFathersName:false,
    isValidMothersName:false,
    isValidSpouseName:false,
    isValidDateOfMarriage:false,
    isValidMothersTongue:true,
    isValidEducation:true,
    isValidOccupation:true,
    isSameAddress:false,
  }
  }

//language: send an array



//priviledge
// SUPER_ADMIN,
//     ADMIN,  
//     GUARDIAN, 
//     VOLUNTEER,
//     USER
