export const requiredDataAllFields={
    
    fname: "",
    mname: "",
    lname: "",
    initiatedName: "",
    gender: "Male",
    odob: "2023-02-23",
    cdob: "2023-02-23",
    caste:"",
    gotra:"",
    maritialStatus: "",
    aspiringAshram: "",
    bloodGroup: "A +ve",
    language: ["HINDI"],
    profileImgUrl: "",
    primaryPhone: '',
    whatsappPhone: '',
    email: '',
    currentAddress: {line1:'',line2:'',
    country:'India',
    state:'Delhi',
    city:'New Delhi',
    pinCode:''},
    permanentAddress: {line1:'',line2:'',
    country:'India',
    state:'Delhi',
    city:'New Delhi',
    pinCode:''},
    connectedTemple: '',
    facilitator: "",
    counselor: "",
    spiritualMaster: "",
    chantingRounds: "",
    yearChantingSince: "",
    yearChanting16Rounds: "",
    introducedBy: "",
    yearOfIntroduction: "",
    previousCounselor: "",
    preferredServices: "",
    servicesRendered: "",
    education: "",
    occupation: "",
    presentDesignation: "",
    skills: "",
    currentCompany: "",
    officeLocation: "",
    birthCity: "",
    birthState: "",
    motherTongue: "Hindi",
    fathersName: "",
    mothersName: "",
    spouseName:"",
    modified: false,
    priviledge:"",
    validations:{isValidFname: false,
    isValidGender:false,
    isvalidAshrama:false,
    isValidBirthCity:false,
    isValidBirthState:false,
    isValidCaste:false,
    isValidGotra:false,
    isValidImageURL:false,
    isSubmitDisabled:true,
    isValidPrimaryNo :false,
    isValidEmail:false,
    isValidCurrentAddress:false,
    isValidPermanentAddress:false,
    isValidCenterConnectedTo:false,
    isValidYearChantingSince:false,
    isValidChantingRounds:false,
    isValidCounselor:false,
    isValidFathersName:false,
    isValidMothersName:false,
    isValidMothersTongue:true,
    isValidEducation:true,
    isValidOccupation:true,
  }
  }

//language: send an array



//priviledge
// SUPER_ADMIN,
//     ADMIN,  
//     GUARDIAN, 
//     VOLUNTEER,
//     USER
